### ISSUE TITLE
LSRO Loss

### ISSUE THREAD

**Issue by a462428** [layumi/Person-reID_GAN#2]
Hi there,

I am confused when I read the detailed code for proposed loss in https://github.com/layumi/Person-reID_GAN/blob/master/matlab/vl_nnloss.m#L291.

I don't know why   "Part2 = (softmax result)-(1/K)?"    in vl_nnloss.m#L298 (Am I rightly understand this code? )

Thx!

**Comment by layumi** [comment]
Hi,
Thank you for using our code.
We write a brief doc for the illustration. 
https://github.com/layumi/Person-reID_GAN/blob/master/support.pdf

**Comment by a462428** [comment]
Thx for ur reply!
