### ISSUE TITLE
main.py_loading

### ISSUE THREAD

**Issue by Zeros12** [layumi/Person-reID_GAN#4]
I am facing the following problem problem when I run " python main.py --dataset duke_128 --train". Please advise regarding the issue.

"Instructions for updating:
Please switch to tf.summary.FileWriter. The interface and behavior is the same; this is just a rename.
 [*] Reading checkpoints...
 [*] Failed to find a checkpoint
 [!] Load failed..."

**Comment by layumi** [comment]
Hi @Zeros12,
I notice that the original DCGAN code have updated.
I will check it soon and update this repos.

**Comment by layumi** [comment]
I move the code to https://github.com/layumi/DCGAN-tensorflow.
And I just tested it. You may have a try.

**Comment by Zeros12** [comment]
thank you so much for you reply.

**Comment by layumi** [comment]
@Zeros12 You are welcomed!
If there are any bugs, just tell me. 
I only test on one machine so somtimes I forget to change some settings.
