### ISSUE TITLE
Unknown parameter 'averageImage'

### ISSUE THREAD

**Issue by why21** [layumi/Person-reID_GAN#5]
Hi, I encountered an error problem when I run the 'train_id_net_res_market_new.m' file. 
The error displayed that 
"
Error using vl_argparse (line 128)
Unknown parameter 'averageImage'

Error in vl_argparse (line 97)
      opts = vl_argparse(opts, vertcat(params,values), varargin{:}) ;

Error in cnn_train_dag (line 47)
opts = vl_argparse(opts, varargin) ;

Error in train_id_net_res_market_K_1 (line 37)
[net,info] = cnn_train_dag(net, imdb, @getBatch,opts) ;"

Could you tell me how to fix it in your spare time? Thanks again for your kindness.

**Comment by layumi** [comment]
You may check two places.
1. In my training code, I defined the value of average image (I just calculated the mean of RGB channels)
https://github.com/layumi/Person-reID_GAN/blob/master/train_id_net_res_market_K_1.m#L16
2. In  cnn_train_dag, there should be an empty value pre-defined. When we call this function, we put our value into it.
https://github.com/layumi/Person-reID_GAN/blob/master/examples/cnn_train_dag.m#L16

Hope it can help you.

**Comment by why21** [comment]
I've solved my problem. Thank you for you reply.
