### ISSUE TITLE
Baseline result is very high

### ISSUE THREAD

**Issue by tyz1994** [layumi/Person-reID_GAN#6]
I use train_id_net_res_market_new ， without GAN data, dataset Market1501, and the final result is  r1-5:  0.8216    0.8679    0.8934    0.9068    0.9192   mAP : 0.6038.  The evaluation code is '*faster', single query.  Is there anyone else who has run the baseline code?

**Comment by layumi** [comment]
Hi @FlyHighest 
Do you change the baseline code?
I notice that the small batchsize can improve the result.

**Comment by tyz1994** [comment]
Thanks for your reply. i change batch size to 10. 
But the same batch size (10) fails to improve LSRO. I got rank1 0.7993.

**Comment by layumi** [comment]
@FlyHighest  It is possible.
We also notice this observation. It also appears in this [ICLR paper](https://openreview.net/pdf?id=H1oyRlYgg).  For some small datasets, small batchsize can do help to aviod the overfitting.
  
In fact, we are planning to discuss and investigate the result in our journal paper. 
P.S. On CUBird dataset, LSRO still works.  

Thank you for your kindly attention.

**Comment by tyz1994** [comment]
Thank you. It helps a lot. I'm looking forward to your new papers.
